### ISSUE TITLE
Bug: doubling rows and columns with xi=0 and yi=0

### ISSUE THREAD

**Issue by sinkra** [dougthor42/wafer_map#30]
Hi Thor,

Wrong expressions in wm_utils.py in

def coord_to_grid(coord, die_size, grid_center):    
    # TODO: seems have a error with negative 0 grid values.
    grid_x = int(grid_center[0] + 0.5 + (coord[0] / die_size[0]))
    grid_y = int(grid_center[1] + 0.5 - (coord[1] / die_size[1]))
    return (grid_x, grid_y)

cause doubling rows and columns with zero index (xi=-0 and yi=0) on wafer map.
I fixed the expressions as follows:

def coord_to_grid(coord, die_size, grid_center):    
    grid_x = int(round(grid_center[0] + (coord[0] / die_size[0])))
    grid_y = int(round(grid_center[1] - (coord[1] / die_size[1])))
    return (grid_x, grid_y)

Regards,
Alexander

**Comment by dougthor42** [comment]
Cool, thanks!

I made the change that you gave me, but I'm not sure if I understood what you meant by
> cause doubling rows and columns
Was it a graphical issue? Do you have a picture of it?

**Comment by sinkra** [comment]
Hi Douglas,

I'm sending a screenshoot with a wafer map example where
columns with Xi=-1 and Xi=0 are blue and white respectively,
while the X index shown in the bottom left is "x0" for both columns.

The same is for rows with Yi=0 and Yi=-1.

Regards,
Alexander

В Вт., 30/06/2015 в 11:03 -0700, Douglas Thor пишет:

**Comment by dougthor42** [comment]
Ah ok, I understand now.

It should be fix thanks to the change you suggested. Thanks!
