### ISSUE TITLE
TypeError: in method 'Menu_Append'

### ISSUE THREAD

**Issue by werdnav** [dougthor42/wafer_map#35]
example.py throws error:
> TypeError: in method 'Menu_Append', expected argument 2 of type 'int'

when running on Linux Mint 17.3, Python 2.7, wxPython 3.0.2.0

wxPython 3.0.2.0 is compiled from source tarball:
https://sourceforge.net/projects/wxpython/files/wxPython/

**Comment by dougthor42** [comment]
Can you try compiling from the latest snapshot build?

http://wxpython.org/Phoenix/snapshot-builds/wxPython_Phoenix-3.0.3.dev1964+f780b21.tar.gz

Note that there is one known regression:
https://github.com/wxWidgets/Phoenix/issues/54

So you'll have to add a single line to `wx/lib/floatcanvas/FCObjects.py` after compiling. See changes in https://github.com/wxWidgets/Phoenix/pull/55.

I'm hoping to have time to create new Linux wheels for dev1964+f780b21 against 2.7 and 3.4 (32-bit and 64-bit) with the 2 required changes (FCObjects.py and core.py) when I get home, so you might be able to use that in the future.

**Comment by werdnav** [comment]
yep, I was compiling wxPython_Phoenix-3.0.3.dev1956+aab2833.tar.gz (I was going off the readme "This was tested using wxPython_Phoenix-3.0.3.dev1956 or higher"); and I can look at wxPython_Phoenix-3.0.3.dev1964+f780b21.tar.gz sometime tomorrow.

**Comment by werdnav** [comment]
Any particular reason for using the dev snapshot as opposed to the last stable release (3.0.2.0)?

**Comment by dougthor42** [comment]
Oh yes, **1956+aab2833** is correct. I looked at the wrong one when giving you the link.

I use the dev snapshot because it supports Py3 and it has some enhancements to other packages (such as lib/plot.py) that I use in other projects.

According to http://www.wxpython.org/download.php#binaries, `3.0.2.0 stable` doesn't support Py3.

**Comment by dougthor42** [comment]
I made Linux wheels for py27 and py34 (64 bit). You can find them at:
https://drive.google.com/folderview?id=0B8kDt4DX9-fRS2tXZFdqYWJsQVE&usp=sharing. They are too big to add to github - I'm looking for an alternate solution. Perhaps building without python-dev or the docs will shrink them. I'll remove them in about a week. Probably.

If you can, try using one of those. I use them for CI, so I needed to make them anyway.

I'll make the 32-bit wheels tomorrow or Wednesday. I hope.

**Comment by werdnav** [comment]
Done. Linux Mint 17.3 (64bit), Python 2.7, wxPython 3.0.3.dev1956+aab2833 (source downloaded, compiled and installed). To confirm the wx version number:
```
> wx.version()
> '3.0.3.dev1956+aab2833 gtk2 (phoenix)'
```
Now example.py returns error:

> AttributeError: Group instance has no attribute 'BoundingBox'

hum... this is getting complicated. Tag 1.0.6 works (on Py2)...

**Comment by dougthor42** [comment]
> AttributeError: Group instance has no attribute 'BoundingBox'

Yeah, that's the regression in Phoenix that I was referring to. My wheels don't have it fixed right now.

You'll need to make the change outlined in https://github.com/wxWidgets/Phoenix/pull/55 and also the change listed at the top of README.md regarding `_Colour___hash__`.

Both are really simple to make, but will get overwritten when a new version of wxPython Phoenix is installed. The devs are aware of both issues.

**Comment by werdnav** [comment]
Are you modifying _Colour___hash__. after compile before install? 

The wafer_map set-up/config may be ok for a standalone app. But if the intention is to add wafer_map to an existing code base, the set-up procedure is way too complicated. Tag 1.0.6 was ideal, it worked out of the box, without modification. I may roll back to that tag, or fork at 1.0.6.

I presume you have your own reasons for using 3.0.3.dev1956 with all the related compromises...

**Comment by werdnav** [comment]
(feel free to mark this issue as resolved for the main branch)

**Comment by dougthor42** [comment]
@werdnav I was able to make 64-bit linux wheels for 2.7 and 3.4 which **include the two required changes**.

You can find both versions at:
https://drive.google.com/folderview?id=0B8kDt4DX9-fROWdjcU9SZnY0TEE&usp=sharing

With this, you *should* be able to just install that file and be all set - no need to manually make any changes.

Please let me know if it doesn't work. It seems to have worked for me, so hopefully it does so for you too.

**Comment by werdnav** [comment]
k, I tried installing the 64-bit wheel earlier today (didn't work). I'll look at this again next week.

**Comment by dougthor42** [comment]
Alright, I think I've done all I can.

+ built Phoenix Linux wheels *with required changes* against Ubuntu 12.04.5 LTS 64-bit
  + Python 2.7.3
  + Python 3.4.4
+ added unit tests for the two required changes
+ updated README.md to provide better install instructions
+ added travis-ci check for your issue as best I can.

----

So, last try:
Download the Python27 64bit wxPython_Phoenix wheel from my GitLab repo [here](https://gitlab.com/dougthor42/wxPython_Phoenix-wheels/blob/master/ubuntu-12.04.5-desktop-amd64/wxPython_Phoenix-3.0.3.dev1956_aab2833-cp27-cp27mu-linux_x86_64.whl). Install it with pip v8.1.1 or higher.
The file: 
+ Has the required changes
+ is a (slightly) more manageable size
+ Has been verified to work on Travis-CI and on an Ubuntu 12.04 virtual machine.

I hope it works for you.
