### ISSUE TITLE
Multiple WaferMaps in same GUI

### ISSUE THREAD

**Issue by jpernia101** [dougthor42/wafer_map#55]
Hey its me again . I was wondering if there was a way to add multiple Wafer Maps onto the same Frame ?
I was thinking maybe creating multiple Panels and generating a wm_app() inside each panel. I'm curios on your thoughts on this approach or if you have a better suggestion I'd be really interested in noting it

**Comment by dougthor42** [comment]
Hmm... I've never tried that before. 

The `wm_app()` object is designed to be completely standalone, so that's not what you want. In theory, you should be able to add multiple `wm_core.WaferMapPanel` panels to your frame. Perhaps something like:

```python
app = wx.App()

class MyFrame(wx.Frame):
    def __init__(self, ...):
        wx.Frame.__init__(...)
        self.wm_panel1 = wm_core.WaferMapPanel(self, data, wafer_info, ...)
        self.wm_panel2 = wm_core.WaferMapPanel(self, data2, wafer_info2, ...)

        self.hbox = wx.BoxSizer(wx.HORIZONTAL)
        self.hbox.Add(self.wm_panel1, 1, wx.EXPAND)
        self.hbox.Add(self.wm_panel2, 1, wx.EXPAND)
        self.SetSizer(self.hbox)

frame = MyFrame('title')
frame.Show()
app.MainLoop()
```

I don't know how having 2 `WaferMapPanel`s will act with shared things, such as the frame's status bar.

**Comment by jpernia101** [comment]
Okay i'll give this a shot and get back to you on how it worked, Thanks again

**Comment by jpernia101** [comment]
sorry it took me so long but it worked out how you said the one thing I did notice was the controls like picking a color or zooming in only works on the last panel added. Any thoughts or ideas on this ? Below is an image of the result of your help haha 
![image](https://user-images.githubusercontent.com/21113685/45958868-23426980-bfde-11e8-9710-eb9ab5cd73ba.PNG)

**Comment by dougthor42** [comment]
Sorry for the delay, quite busy. I see that you closed this issue - did you figure things out? If so, care sharing what you've found?

I think you'll have to rebind events for each WaferMapPanel individually. Perhaps monkeypatching `WaferMapPanel._bind_events()` before instancing?

**Comment by jpernia101** [comment]
you're fine , I thought you didn't reply maybe because you wanted me to create a new issue. I didn't figure out the scroll thing because I have bigger issues like trying to display only 9 wafers per frame and I just started learning WXpython so I'm having a learning curve right now with sizers. later on down the road i'll give the scrolling thing another attempt
