### ISSUE TITLE
wm_core.WaferMapPanel issue with wx.Notebook

### ISSUE THREAD

**Issue by jpernia101** [dougthor42/wafer_map#57]
so my approach here is to have a list of wx.panels called **listOfWaferPanels** and 2 other list called **listOfGridSizers** & **listOfPanels** . What I was trying to do is have my gridsizer be a size of 9 and for the extra wm_core.WaferMapPanel in my my list of wafer panels then add the additional ones to the next tab. Then I wanted to add those parent panels to my notebook but im running into an issue
- The first 9 seem to load correctly and accurately but whenever I switch tabs it displays the exact same 9 wafers that were in the first tab. I'm not sure whats going on here because when I run the debugger it seems that the different panels do contain different data & are being added to the notebook.

Below is the code ...maybe you can see what i'm missing

`
    

    listOfWaferPanels = []
    listOfGridSizers = []
    listOfPanels = []
    waferNum = 0 
    for lotID, wafNum in df3.groupby(['LOT_WF']):
            df4 = wafNum[['X_COORD', 'Y_COORD', 'HB_NUM']]
            print(wafNum)
            print("\n")
            my_list = df4.transform(tuple, axis=1).tolist()
            temp_panels = wm_core.WaferMapPanel(self, my_list, waferDesign, data_type='discrete'.lower())
            listOfWaferPanels.append(temp_panels)
            waferNum += 1
    tabNumber = 0 
        numOfTabs = (waferNum//9) + 1
        for tab in range(numOfTabs):
            tempGridSizers = wx.GridSizer(3,3,1.5,1.5)
            tempPanel = wx.Panel(self.waferTab,wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.TAB_TRAVERSAL 
            listOfGridSizers.append(tempGridSizers)
            listOfPanels.append(tempPanel)
    for i in range(waferNum):
            listOfGridSizers[i//9].Add(listOfWaferPanels[i], 1 , wx.EXPAND
    for tab in range(numOfTabs):
            tabString = ("Page"+ str(tabNumber))    
            listOfPanels[tab].SetSizer(listOfGridSizers[tab])
            listOfPanels[tab].Layout()
            listOfGridSizers[tab].Fit( listOfPanels[tab] )
            self.waferTab.AddPage(listOfPanels[tab], tabString, select=False)
            tabNumber += 1
            bSizer6.Add(self.waferTab ,1, wx.EXPAND |wx.ALL, 5)
        self.SetSizer( bSizer6 )
        self.Layout()
        
        self.Centre( wx.BOTH )
`
whenever I click on both tabs shown in the image I get the exact same image on the other tab .
![capture1](https://user-images.githubusercontent.com/21113685/46428837-a1072300-c70a-11e8-9c48-0aa54259f621.PNG)

**Comment by dougthor42** [comment]
I've never used `wx.Notebook` before, so I don't think I'll be of much help. However, your comment "whenever I switch tabs it displays the exact same 9 wafers" makes me think that it's a repainting issue.

Perhaps try adding a [`wx.Windows.Refresh()`](https://wxpython.org/Phoenix/docs/html/wx.Window.html?highlight=wx.window#wx.Window.Refresh) somewhere in there?

**Comment by jpernia101** [comment]
I actually figured it out not too long ago 
I wasn't assigning the Wafer map panel the correct parent in the line 

`temp_panels = wm_core.WaferMapPanel(self, my_list, waferDesign, data_type='discrete'.lower())
`

I replaced 'self' with the correct parent panel and boom it worked
