### ISSUE TITLE
Constant Colors in Legend 

### ISSUE THREAD

**Issue by jpernia101** [dougthor42/wafer_map#58]
Hey thanks for being responsive on this library you've made it really has helped me w/ this project. My question here is the following 
1- Is there anyway to constantly make the legend colors the same. I have several wafers in the same panel an I would like "1" to always be the same color
2- is there a way to organize the Legend constantly. For example "1" may be the first option on my legend but in another wafer "1" would be the 5th element in my legend.
I just want to be able to do these things to have my wafers look uniform 
Below is an image of what I'm referring to 
![capture](https://user-images.githubusercontent.com/21113685/46627611-9f6d9e80-cb00-11e8-8e5b-ab4304974f43.PNG)

The 2nd wafer shown has "1" as the 4th option instead of the 1st legend item. I would like to be able to have control of the legend so I can pick the order and the color. Just wondering if the library has option to do the latter.

Once again thank you for getting back to me.

**Comment by jpernia101** [comment]
I've tried using the parameter **discrete_legend_values** in the init statement of the WaferMapPanel but I seem to always get an error I tried putting a list into the parameter but im obviously not doing something right. I do see that you have a TODO for that documentation . 
`if self.data_type == "discrete":

            if self.discrete_legend_values is None:

                unique_items = list({_die[2] for _die in self.xyd})

            else:

                unique_items = self.discrete_legend_values

            self.legend = wm_legend.DiscreteLegend(self,

                                                   labels=unique_items,

                                                   colors=None,

                                                   )`
That's the part that I read but I'm missing something

**Comment by dougthor42** [comment]
Hmm... Reading the code, it looks like `discrete_legend_values` should indeed take a list.

What error are you getting when you try?

> 1- Is there anyway to constantly make the legend colors the same. I have several wafers in the same panel an I would like "1" to always be the same color

I think the only way to do this is to use the `discrete_legend_values` option, like you're trying to do.

> 2- is there a way to organize the Legend constantly. For example "1" may be the first option on my legend but in another wafer "1" would be the 5th element in my legend.

Same as above - I think `discrete_legend_values` is the way to go. By default, the `discrete` option simply iterates through your die data looking for values and then takes a set of that. Python sets are unordered, and thus so is the legend.

----

I've got a bit of time this morning so I'll see if I can figure things out. However, having the error traceback would be super helpful.

**Comment by jpernia101** [comment]
so I am still stuck on this , below is the call I tried to do
`
for i in range(waferNum):
    temp = wm_core.WaferMapPanel(listOfPanels[i//9], listOfTuples[i], waferDesign, data__type='discrete'.lower() , show_die_gridlines= False, discrete_legend_values = ['a','b','c'])
                 `
those legend values don't really mean nothing to me, I was just trying some random inputs to see if they work , I actually want the values to be the "d" values of xyd but I couldn't even get those simple ones to work below is an image of the error I keep on getting 

![capture](https://user-images.githubusercontent.com/21113685/46748948-66593980-cc7a-11e8-97ec-23d9c16ddafb.PNG)

**Comment by jpernia101** [comment]
let me know if you want me to repost the code for some reason the formatting was off

**Comment by dougthor42** [comment]
> let me know if you want me to repost the code for some reason the formatting was off

Actually I just edited it 😄.  You can use tripple-backticks \``` to create a code block. And if you add a language after them, it will add syntax highlighting. Like so:

```
    ```python
    for i in range(5):
        pass
    ```
```

----

Ah, `KeyError`. Looks like you're not adding all values from `rcd` into your `discrete_legend_values` variable.

(Note: I actually just pushed an update to the docs in #60 to make things a little more clear).

I'm assuming your `listOfTuples` variable is a `list of [list of xyd tuples]` (see below for example). Give this a shot:

```python
# get a set of all die values in all the data, then convert to a list and sort it.
# Note that we want to do this *outside* of the loop, since it's not guaranteed
# that every wafer have all the same bin values
legend_values = sorted(list({x[2] for _w in listOfTuples for x in _w}))
for i in range(waferNum):
    temp = wm_core.WaferMapPanel(..., discrete_legend_values=legend_values)
```

Note, the list comprehension above could also be written as (though slower):
```python
legend_values = set()
for _w in listOfTuples:    # _w stands for "wafer"
    for x in _w:
        legend_values.add(x[2])
legend_values = sorted(list(legend_values))
```

`list of [list of xyd tuples]` looking something like:

```python
[
    # wafer 0
    [(1, 1, "B"), (1, 2, "B"), (2, 1, "A"), (2, 2, "C")],
    # wafer 1
    [(1, 1, "C"), (1, 2, "D"), (2, 1, "A"), (2, 2, "A")],
    ...
]
```

**Comment by jpernia101** [comment]
so I tried the mentioned above but now it seems all my wafers have the same legend even though some of them don't even have the values in the legend. I put it outside the **For ** loop as well and yes you are right to assume that the listofTuples is my xyd 
I tried 

'''

legend_values = sorted(list({x[2] for _w in listOfTuples for x in _w}))

            for i in range(waferNum):
                temp = wm_core.WaferMapPanel(listOfPanels[i//9], listOfTuples[i], waferDesign, data_type='discrete'.lower() , show_die_gridlines= False, discrete_legend_values = legend_values)
                #temp._create_legend(self)
                listOfWaferPanels.append(temp)
'''
and the output is this 
![image](https://user-images.githubusercontent.com/21113685/46752922-02d40980-cc84-11e8-85d7-52917df3d413.png)

notice how they all have the same output

**Comment by jpernia101** [comment]
oops just noticed ..sorry my listOfTuples is actually formatted like this 


`
[(1,1,1), (1,2,45), (1,3,56)]
`

instead of a 
`
list of [list of xyd tuples]
`

**Comment by dougthor42** [comment]
FYI: you want 3 backticks `` ` ``  (same as the tilde <kbd>~</kbd> key on a US Keyboard layout) instead of single quotes `'` for your code blocks.

> all my wafers have the same legend even though some of them don't even have the values in the legend

OK, I misunderstood your request. You want to have the same legend colors across all wafers, but only show items in the legend that actually exist on the wafer. Is this correct?

It's possible but will take some smart coding. You'll need to:

1.  Define your global legend label list (same way as above using that list comprehension).
2.  Define a global legend color list. You can call `wm_legend.DiscreteLegend.create_colors(n)` to do this.
     + Note that this is an instance method, so you have to instantiate it first with some dummy data and then send in the length of your global legend label list
    + I'll make a note to change this to a class method (or just a utils function) in the future.
3.  Figure out which die data (bin) values exist in each wafer.
4.  Create your own `wm_legend.DiscreteLegend` instances, one for each wafer. adjusting `labels` and `colors` according to the info from <span>#</span>3.
5.  Set `WaferMapPanel.legend` to the value from <span>#</span>4.

**Comment by jpernia101** [comment]
okay , i'll give this a shot and let you know if it works. I believe I understand what you're saying , if not i'll ask you about it, if that's cool

**Comment by jpernia101** [comment]
actually one question for step 1 should my loop changes since my listOfTuples is actually formatted
``
[(),(),(), ...]
``
rather than
``
[  [(),(),()] ,  [(),(),()],  [(),(),()], ….. ]
``

**Comment by dougthor42** [comment]
If *all* of your data (meaning all 9 wafers) is in listOfTuples like `[(), (), (), ...]` then yes that should work for your global legend label list. You might need to adjust the list comprehension though.

**Comment by jpernia101** [comment]
okay so im having some issues w/ number 2 ..I figured out number 1&3 but im having some issues with the ``wm_legend.DiscreteLegend.create_colors(n) `` im assuming it has something to do with the instance thing you mentioned above.  Below is the code and the error I was getting for it. Also in the code is step number 3 where I created a list of list with the correct binning for each wafer 
```
            legend_values_global = sorted({x[2] for _w in listOfTuples for x in _w})
            bins = []
            for bracket in listOfTuples:
                bins.append([bracket[i][2] for i in range(len(bracket))])
            print(bins[0])
            legend_colors_global = wm_legend.DiscreteLegend.create_colors(len(legend_values_global))
```
so   ``legend_values_global    ``
would be the complete list of all the possible bins 
and ``bins ``  is a list of list containing the bins for the corresponding wafer`` [[1,2,3,4,5] , [1,2,3,39,12]]``
but I get this error when trying to use ``wm_legend.DiscreteLegend.create_colors ``


![image](https://user-images.githubusercontent.com/21113685/46765462-b51bc900-cca4-11e8-8031-3095d97a47cf.png)

**Comment by dougthor42** [comment]
The error is indeed saying that you didn't initialize `DiscreteLegend`, though it's saying it indirectly.

However, looking at the code some more I've come to the conclusion that it would be easier to simply make a new function rather than monkeypatch `DiscreteLegend` (Why? Turns out you'd have to patch `__init__` and it's this whole thing... all around not fun).

So place this somewhere in your project:

```python
def create_colors(n):
    """
    Create the colors based on how many legend items there are (n).
    """
    spacing = 360 / n
    colors = []
    for val in wm_utils.frange(0, 360, spacing):
        hsl = (val/360, 1, 0.75)
        colors.append(colorsys.hsv_to_rgb(*hsl))

    # convert from 0-1 to 0-255 and return
    colors = [tuple(int(i*255) for i in color) for color in colors]

    # Alternate colors across the circle
    colors = colors[::2] + colors[1::2]
    return colors
```

This function is literally a copy-paste of `wm_legend.DiscreteLegend.create_colors` with the call signature changed to remove the `self` argument (and the docstring shortened).

And then call it here:

```python
legend_colors_global = create_colors(len(legend_values_global))
```

**Comment by jpernia101** [comment]
ive done what you just suggested and I got a few questions 
1-in step 3 I created a list of list that has all the bins for the corresponding wafers it includes duplicates should I make my list just the unique values for that wafer or should I keep the duplicates 
2- I have 1-3 done in that procedure you told me to follow do I keep the same and try 4 & 5 just like you said or should I switch something up there as well

Thanks for being so responsive btw I would be so lost w/o it

**Comment by jpernia101** [comment]
so I decided to remove the duplicates from my list and just keep the unique ones I need for each wafer and moved on to step 4 & 5 but I keep getting the same error which i'll show below along w/ the code that I tried 
```
legend_values_global = sorted({x[2] for _w in listOfTuples for x in _w})
            bins = []
            uniqueBins = []
            for bracket in listOfTuples:
                bins.append(sorted([bracket[i][2] for i in range(len(bracket))]))
 
            legend_colors_global = create_colors(len(legend_values_global))
            for bracket in bins:
                uniqueBins.append(list(sorted(set(bracket))))
                
            for i in range(waferNum):
                
                temp = wm_core.WaferMapPanel(listOfPanels[i//9], listOfTuples[i], waferDesign, data_type='discrete'.lower() , show_die_gridlines= False)
                tempLegend = wm_legend.DiscreteLegend(temp, labels= uniqueBins[i] , colors= None)
                temp.legend(tempLegend)
``` 

the error that keeps displaying says 
`
 temp.legend(tempLegend)
TypeError: 'DiscreteLegend' object is not callable
`

I think it's almost working might be missing something small here

**Comment by jpernia101** [comment]
okay so it ran but it gave me the same result as usual except it appears to have attempted to create a legend at the top left of every panel 
![image](https://user-images.githubusercontent.com/21113685/46816242-28274d00-cd42-11e8-95a5-285388f72dc2.png)

but after that failed I went ahead and just passed the `uniqueBins` to the parameter as shown right below
``temp = wm_core.WaferMapPanel(listOfPanels[i//9], listOfTuples[i], waferDesign, data_type='discrete'.lower() , show_die_gridlines= False, discrete_legend_values = uniqueBins[i])``


and that actually worked for the order of the bins still not to sure how to make the colors predictable but its some progress.
![capture](https://user-images.githubusercontent.com/21113685/46816500-b6033800-cd42-11e8-9a3f-84f383b82e79.PNG)

**Comment by jpernia101** [comment]
so I stayed w/ the plan you told me and I went ahead and made dictionaries for each pair wafer key:value and its printing correctly but on the actual wafer it seems to be stuck on the old legend. Whenever I call ``temp.legend = temple`` it seems that its on the background but no on the wafer here is the code and the image im getting 

```
legend_values_global = sorted({x[2] for _w in listOfTuples for x in _w})
            bins = []
            uniqueBins = []
            for bracket in listOfTuples:
                bins.append(sorted([bracket[i][2] for i in range(len(bracket))]))         
            legend_colors_global = create_colors(len(legend_values_global))
            for bracket in bins:
                uniqueBins.append(tuple(sorted(set(bracket))))
            global_dict = dict(zip(legend_values_global, legend_colors_global))

    
            keyValues = []
            
            for i in range(waferNum):
                for p in uniqueBins:
                    keyValues.append({k: global_dict[k] for k in p}) 
                labels, colors = list(zip(*sorted(keyValues[i].items())))
                temp = wm_core.WaferMapPanel(listOfPanels[i//9], listOfTuples[i], waferDesign, data_type='discrete'.lower() , show_die_gridlines= False)
                tempLeg = wm_legend.DiscreteLegend(temp, labels,colors)
                temp.legend = tempLeg
                listOfWaferPanels.append(temp)
```

![image](https://user-images.githubusercontent.com/21113685/46834039-e1504c00-cd6f-11e8-94c0-37cdf10ac430.png)

you can see at the top left of each corner a little small square what appears to be a legend but the default one is covering it

**Comment by dougthor42** [comment]
Hey @jpernia101, I've pushed some updates and a new version (v1.1.0) which includes an option to send a color list to the WaferMapPanel constructor. This should make things a lot easier for you.

You no longer need to overwrite `WaferMapPanel.legend`. Instead, you can just send in your legend labels and colors directly to the WaferMapPanel constructor. I've also made `create_colors` a static method so you don't have to re-implement it yourself.

Your code should now look something like:

```python
legend_values_global = sorted({x[2] for _w in listOfTuples for x in _w})
bins = []
uniqueBins = []
for bracket in listOfTuples:
    bins.append(sorted([bracket[i][2] for i in range(len(bracket))]))
# I've switched to using the static method `DiscreteLegend.create_colors(n)`
legend_colors_global = DiscreteLegend.create_colors(len(legend_values_global))
for bracket in bins:
    uniqueBins.append(tuple(sorted(set(bracket))))
global_dict = dict(zip(legend_values_global, legend_colors_global))

keyValues = []
            
for i in range(waferNum):
    for p in uniqueBins:
        keyValues.append({k: global_dict[k] for k in p}) 
    labels, colors = list(zip(*sorted(keyValues[i].items())))
    temp = wm_core.WaferMapPanel(
        listOfPanels[i//9],
        listOfTuples[i],
        waferDesign,
        # there's a new Enum for data_type that you can (optionally) use.
        data_type=wm_constants.DataType.DISCRETE,
        show_die_gridlines= False,
        discrete_legend_values=labels,
        discrete_legend_colors=colors,
    )
    # no longer need to overwrite `temp.legend` because we send in the labels and colors to
    # the `WaferMapPanel` constructor.
    listOfWaferPanels.append(temp)
```

Final comments:
1. Please use the "Preview" tab in GitHub when writing issues and comments so that you can make sure your notes are easy to read.
2. Please read over PEP8 and start making your code follow those guidelines. It's the standard for python development and if you want to continue with Python, anyone else you collaborate with will greatly appreciate it :grin:.

**Comment by dougthor42** [comment]
Correction: Use version 1.1.1 - I forgot to actually push the static method part in v1.1.0.

**Comment by jpernia101** [comment]
wow Doug it works great !! thanks so much honestly this was tough but you saw it all the way through even though you didn't have to ! I really appreciate it youre my favorite person online ever thanks again !


![image](https://user-images.githubusercontent.com/21113685/46888953-a3166380-ce27-11e8-8d54-2e8d97209777.png)

**Comment by jpernia101** [comment]
I will look at the Python guidelines btw I just have this wafer map project to turn in for a deadline . Thanks for the tip

**Comment by dougthor42** [comment]
Glad to hear things worked out! ✨🎉

**Comment by mesmerise** [comment]
Hi @jpernia101, I'm new to Python and Github and I wonder if you would be willing to share (parts) of your code on how to open multiple maps in parallel with a common color scale. Any help would be greatly appreciated. All the best, Andy
