### ISSUE TITLE
Legend display gets Cut-Off on smaller screen displays 

### ISSUE THREAD

**Issue by jpernia101** [dougthor42/wafer_map#74]
Hey Doug im pretty much done w/ my project now but I have one last nagging issue that I haven't been able to resolve. I have two screens where I run my program the bigger one is 2400x1300 and it displays the legend correctly but on my smaller display 1920x1030 the legend gets cut off. Any ideas on how to go around this ?  below is an image of the example.
![3__2018-10-22](https://user-images.githubusercontent.com/21113685/47310324-58050900-d5fc-11e8-8c7b-b1ceee2a2da4.png)

**Comment by jpernia101** [comment]
UPDATE : I used the method ``toggle_legend()`` and it removed most of the legend on each wafer but it kept the one small square on each one. the code and image is shown below 
```
temp = wm_core.WaferMapPanel(listOfPanels[i//30], listOfTuples[i], waferDesign, data_type='discrete'.lower() , show_die_gridlines= False )
temp.toggle_legend()
listOfWaferPanels.append(temp)
``` 
![image](https://user-images.githubusercontent.com/21113685/47316778-85a67e00-d60d-11e8-86b2-3c155e0514a4.png)

I also tried to do 
```
temp = wm_core.WaferMapPanel(listOfPanels[i//30], listOfTuples[i], waferDesign, data_type='discrete'.lower() , show_die_gridlines= False )
temp.legend_bool = False
temp.toggle_legend()
listOfWaferPanels.append(temp)
```
and I got an error that said ``wx._core.wxAssertionError: C++ assertion "!sizer || m_containingSizer != sizer" failed at ..\..\src\common\wincmn.cpp(2470) in wxWindowBase::SetContainingSizer(): Adding a window to the same sizer twice?``

when I set the ``temp.legend_bool = False`` to ``temp.legend_bool = True`` I got the same result I did on the image shown above

**Comment by dougthor42** [comment]
I'm unable to reproduce the issue - can you post a bit more code? Do you have a git repo for the project that I could look at?

Setting `legend_bool` after initializing the `WaferMapPanel` won't help you - at that point the legend has already been made. The correct way is to use `toggle_legend()` as you found. (I really ought to make `legend_bool` and a bunch of other attributes private...)

One thing you can try is hacking `WaferMapPanel._init_ui()`. Find the source code for it, copy it into your project, and remove the `self._create_legend()` line. Then overwrite the default function before you initialize any wafer maps:

```python
def my_init_ui(self):
    ...

wm_core.WaferMapPanel._init_ui = my_init_ui          # note no parentheses
temp = wm_core.WaferMapPanel(...
```

**Comment by jpernia101** [comment]
no I don't have a Git repo for it but I found at intial load the legend does disappear but when I click on another tab from the notebook the little square appears again. My guess is that when it goes through the loop it keeps on toggling the legend on/off therefore resulting in that little square 

```
for i in range(waferNum):
   for p in uniqueBins:
       keyValues.append({k: global_dict[k] for k in p}) 
    labels, colors = list(zip(*sorted(keyValues[i].items())))
    temp = wm_core.WaferMapPanel(listOfPanels[i//9], listOfTuples[i], waferDesign, data_type='discrete'.lower() , show_die_gridlines= False,discrete_legend_values =labels,discrete_legend_colors =colors )
    temp.toggle_legend()
    listOfWaferPanels.append(temp)
    tempBox = wx.BoxSizer(wx.VERTICAL)
    boxText = wx.StaticText( listOfPanels[i//9], wx.ID_ANY, flat_list[i][0], wx.DefaultPosition, wx.DefaultSize, 0 )
    boxText.Wrap(-1)
           
    tempBox.Add(boxText,0, wx.ALIGN_CENTER|wx.ALL, 0 )
    tempBox.Add( listOfWaferPanels[i], 1, wx.EXPAND |wx.ALL, 5 )
    listOfGridSizers[i//9].Add(tempBox, 1 , wx.EXPAND)
```

the image below is how it looks at first load 
![image](https://user-images.githubusercontent.com/21113685/47514956-38155580-d847-11e8-86f3-00d697a4e020.png)
 but when I click on the next tab the little square appears again
![image](https://user-images.githubusercontent.com/21113685/47515014-59764180-d847-11e8-805c-e386e3440a5e.png)
after that the little square appears in all of them including the beginning one
