### ISSUE TITLE
apply for a permission about i can commit my demo 

### ISSUE THREAD

**Issue by irkchen** [dougthor42/wafer_map#78]
Dear sir, please give me a permission that i can commit my demo about client can move select areas die,click choose one die,thank you

**Comment by dougthor42** [comment]
Please submit a Pull Request (PR) and I'll review the code.

If you need help submitting the PR, please see here: https://help.github.com/en/articles/about-pull-requests

**Comment by irkchen** [comment]
ok sir.I will check my demo and commit In next time
